name: Manga Check Cron Job

on:
  schedule:
    - cron: '*/15 * * * *' # A cada 15minutos
  workflow_dispatch: # Permite a execução manual

jobs:
  check-manga:
    runs-on: ubuntu-latest

    steps:
      - name: Request to check manga updates
        run: |
          curl -X GET https://wslibrary.werioliveira.site/api/mangas \
          -H "GitHub-Action: eKZ8IyclYXm9msLG3YGJ0WVQwTfzqDVGTerW8X9MMKukrP72r9dC2Y5Jl4zzzY7c"
